"""Boundary tests for the frozen Brain runtime dependency authority."""

from __future__ import annotations

import hashlib
import re
import stat
from copy import deepcopy
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2]
RUNTIME_LOCK = ROOT / "requirements.lock"
DEV_LOCK = ROOT / "requirements-dev.lock"
BASE_DIGEST = "sha256:16f75ad0fbc6c4883a8afd63b2d700c3cf68ccffc1aaeca5304ca0a3a908451f"
DOCKER_BUILDER_DIGEST = "sha256:e036091375b816e40f07620582d1dfaa0e2c2da58ea5731fdcf560534b2a4a57"
RUNTIME_COMMAND = (
    "uv pip compile pyproject.toml --python-version 3.13 --python-platform "
    "x86_64-unknown-linux-gnu --generate-hashes --output-file requirements.lock"
)
DEV_COMMAND = (
    "uv pip compile pyproject.toml --extra dev --python-version 3.13 --python-platform "
    "x86_64-unknown-linux-gnu --generate-hashes --output-file requirements-dev.lock"
)


def _locked_entries(path: Path) -> dict[str, str]:
    entries = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^([a-z0-9][a-z0-9._-]*)==([^ ;\\]+)", line)
        if match:
            entries[match.group(1).replace("_", "-").lower()] = match.group(2)
    return entries


@pytest.mark.parametrize(
    ("path", "command"),
    [(RUNTIME_LOCK, RUNTIME_COMMAND), (DEV_LOCK, DEV_COMMAND)],
)
def test_locks_are_exact_linux_amd64_uv_outputs(path: Path, command: str) -> None:
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# This file was autogenerated by uv via the following command:\n")
    assert f"#    {command}\n" in text
    assert "--hash=sha256:" in text
    assert " @ " not in text
    assert "-e " not in text
    assert _locked_entries(path)
    requirement_lines = [line for line in text.splitlines() if re.match(r"^[a-z0-9]", line)]
    assert all("==" in line for line in requirement_lines)


def test_deploy_owner_derives_and_compares_the_repository_lock_and_inventory() -> None:
    from scripts.staging import deploy_open_intelligence_job as deployer
    from scripts.staging import run_live_intelligence_brain as runtime

    lock_digest = hashlib.sha256(RUNTIME_LOCK.read_bytes()).hexdigest()
    locked = runtime._lock_versions(RUNTIME_LOCK.read_bytes())
    distributions = (
        *locked.items(),
        ("pip", "26.2.1"),
        ("trends-engine-v2", "0.1.0"),
    )
    inventory = runtime._runtime_inventory_payload(
        distributions=distributions,
        locked_versions=locked,
    )
    sbom_digest = hashlib.sha256(inventory).hexdigest()
    derived = deployer.derive_brain_dependency_authority(
        lock_path=RUNTIME_LOCK,
        supplied_dependency_lock_sha256=lock_digest,
        supplied_runtime_sbom_sha256=sbom_digest,
    )
    assert derived.dependency_lock_sha256 == lock_digest
    assert derived.runtime_sbom_sha256 == sbom_digest

    with pytest.raises(deployer.DeploymentError, match="dependency lock"):
        deployer.derive_brain_dependency_authority(
            lock_path=RUNTIME_LOCK,
            supplied_dependency_lock_sha256="f" * 64,
            supplied_runtime_sbom_sha256=derived.runtime_sbom_sha256,
        )
    with pytest.raises(deployer.DeploymentError, match="runtime SBOM"):
        deployer.derive_brain_dependency_authority(
            lock_path=RUNTIME_LOCK,
            supplied_dependency_lock_sha256=lock_digest,
            supplied_runtime_sbom_sha256="f" * 64,
        )


@pytest.mark.parametrize("name", ["pip", "trends-engine-v2"])
def test_deploy_inventory_rejects_overlapping_authority_classes(tmp_path: Path, name: str) -> None:
    from scripts.staging import deploy_open_intelligence_job as deployer

    lock = tmp_path / "requirements.lock"
    lock.write_text(
        f"{name}==1.0.0 \\\n+    --hash=sha256:" + "1" * 64 + "\n",
        encoding="utf-8",
        newline="\n",
    )
    digest = hashlib.sha256(lock.read_bytes()).hexdigest()
    with pytest.raises(deployer.DeploymentError, match="overlap"):
        deployer.derive_brain_dependency_authority(
            lock_path=lock,
            supplied_dependency_lock_sha256=digest,
            supplied_runtime_sbom_sha256="f" * 64,
        )


def test_each_locked_distribution_requires_its_own_hash() -> None:
    from scripts.staging import run_live_intelligence_brain as cli

    malformed = ("first==1.0.0\nsecond==2.0.0 \\\n+    --hash=sha256:" + "1" * 64 + "\n").encode()
    with pytest.raises(cli.RuntimeIdentityRefusal, match="hash"):
        cli._lock_versions(malformed)


def test_docker_and_cloud_build_use_only_the_approved_frozen_installs() -> None:
    docker = (ROOT / "Dockerfile.staging").read_text(encoding="utf-8")
    cloudbuild = (ROOT / "cloudbuild.staging.yaml").read_text(encoding="utf-8")
    approved_from = f"FROM --platform=linux/amd64 python:3.13-slim@{BASE_DIGEST}"
    assert approved_from in docker
    assert "requirements.lock ./" in docker
    assert "pip install --require-hashes -r requirements.lock" in docker
    assert "pip install --no-deps . --no-build-isolation" in docker
    assert "pip install -e" not in docker
    assert "/app/runtime-distributions.json" in docker
    assert "/app/runtime-distributions.sha256" in docker
    assert "chmod 0444" in docker
    test_docker = (ROOT / "Dockerfile.tests").read_text(encoding="utf-8")
    assert approved_from in test_docker
    assert "pip install --require-hashes --no-compile -r /tmp/requirements-dev.lock" in test_docker
    assert "pip install --no-deps . --no-build-isolation" not in test_docker
    assert f"name: gcr.io/cloud-builders/docker@{DOCKER_BUILDER_DIGEST}" in cloudbuild
    assert "Dockerfile.tests" in cloudbuild
    assert "pip install -e" not in cloudbuild
    assert "name: python:3.13\n" not in cloudbuild
    assert "Dockerfile.staging" in cloudbuild
    for forbidden in ("gcloud ", " run jobs ", " push", "images:"):
        assert forbidden not in cloudbuild


def test_inventory_is_complete_canonical_and_accepts_only_pip_as_base_supplied() -> None:
    from scripts.staging import run_live_intelligence_brain as cli

    payload = cli._runtime_inventory_payload(
        distributions=(
            ("trends-engine-v2", "0.1.0"),
            ("google_auth", "2.40.0"),
            ("pip", "26.2.1"),
        ),
        locked_versions={"google-auth": "2.40.0"},
    )
    assert payload == (
        b'[{"name":"google-auth","source":"locked","version":"2.40.0"},'
        b'{"name":"pip","source":"base_image_supplied","version":"26.2.1"},'
        b'{"name":"trends-engine-v2","source":"local_project","version":"0.1.0"}]'
    )

    with pytest.raises(cli.RuntimeIdentityRefusal, match="base image"):
        cli._runtime_inventory_payload(
            distributions=(("pip", "26.2.1"), ("wheel", "0.46.1")),
            locked_versions={},
        )


def test_runtime_files_recompute_lock_inventory_and_sbom_before_authority(
    tmp_path: Path,
) -> None:
    from scripts.staging import run_live_intelligence_brain as cli

    lock = tmp_path / "requirements.lock"
    lock.write_text(
        "google-auth==2.40.0 \\\n+    --hash=sha256:" + "1" * 64 + "\n",
        encoding="utf-8",
        newline="\n",
    )
    inventory = cli._runtime_inventory_payload(
        distributions=(
            ("google-auth", "2.40.0"),
            ("pip", "26.2.1"),
            ("trends-engine-v2", "0.1.0"),
        ),
        locked_versions={"google-auth": "2.40.0"},
    )
    inventory_path = tmp_path / "runtime-distributions.json"
    inventory_path.write_bytes(inventory)
    digest = hashlib.sha256(inventory).hexdigest()
    digest_path = tmp_path / "runtime-distributions.sha256"
    digest_path.write_text(digest + "\n", encoding="ascii", newline="\n")
    inventory_path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
    digest_path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)

    result = cli._verify_runtime_files(
        lock_path=lock,
        inventory_path=inventory_path,
        inventory_digest_path=digest_path,
        dependency_lock_sha256=hashlib.sha256(lock.read_bytes()).hexdigest(),
        runtime_sbom_sha256=digest,
        distributions=(
            ("pip", "26.2.1"),
            ("google-auth", "2.40.0"),
            ("trends-engine-v2", "0.1.0"),
        ),
    )
    assert result == {
        "dependency_lock_sha256": hashlib.sha256(lock.read_bytes()).hexdigest(),
        "runtime_sbom_sha256": digest,
    }
    inventory_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    inventory_path.write_bytes(inventory + b" ")
    with pytest.raises(cli.RuntimeIdentityRefusal, match="inventory"):
        cli._verify_runtime_files(
            lock_path=lock,
            inventory_path=inventory_path,
            inventory_digest_path=digest_path,
            dependency_lock_sha256=hashlib.sha256(lock.read_bytes()).hexdigest(),
            runtime_sbom_sha256=digest,
            distributions=(("pip", "26.2.1"),),
        )


def _runtime_authority(tmp_path: Path, monkeypatch):
    from scripts.staging import run_live_intelligence_brain as cli
    from src.analysis.open_intelligence import execution_approval

    lock = tmp_path / "requirements.lock"
    lock.write_text(
        "google-auth==2.40.0 \\\n+    --hash=sha256:" + "1" * 64 + "\n",
        encoding="utf-8",
        newline="\n",
    )
    distributions = (
        ("google-auth", "2.40.0"),
        ("pip", "26.2.1"),
        ("trends-engine-v2", "0.1.0"),
    )
    inventory = cli._runtime_inventory_payload(
        distributions=distributions,
        locked_versions={"google-auth": "2.40.0"},
    )
    inventory_path = tmp_path / "runtime-distributions.json"
    inventory_path.write_bytes(inventory)
    digest_path = tmp_path / "runtime-distributions.sha256"
    digest_path.write_text(hashlib.sha256(inventory).hexdigest() + "\n", encoding="ascii")
    inventory_path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
    digest_path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
    monkeypatch.setattr(cli, "_RUNTIME_LOCK_PATH", lock)
    monkeypatch.setattr(cli, "_RUNTIME_INVENTORY_PATH", inventory_path)
    monkeypatch.setattr(cli, "_RUNTIME_INVENTORY_DIGEST_PATH", digest_path)

    arguments = (
        "--target",
        "staging",
        "--run-id",
        "run_20260903_dynamic_apply_v2_r16",
        "--signal-id",
        "sig_" + "e" * 64,
        "--research-depth",
        "briefing",
    )
    # The job the v2 deployer renders: job, principal and image namespace from the
    # active origin's brain_read binding, the durable environment, and the eight
    # annotations including the trusted generation pair.
    profile = cli._brain_profile()
    task = {
        "containers": [
            {
                "image": profile.image_repository + "@sha256:" + "a" * 64,
                "command": ["python"],
                "args": [cli._BRAIN_SCRIPT, *arguments],
                "env": [
                    {"name": name, "value": value}
                    for name, value in execution_approval._DEFAULT_ENVIRONMENT
                ],
                "resources": {"limits": {"memory": "4Gi"}},
                "volumeMounts": [],
            }
        ],
        "serviceAccount": profile.service_identity,
        "maxRetries": 0,
        "timeout": "900s",
        "volumes": [],
    }
    annotations = {
        "42.ogilvy/contract-sha256": cli._CONTRACT_SHA256,
        "42.ogilvy/dependency-lock-sha256": hashlib.sha256(lock.read_bytes()).hexdigest(),
        "42.ogilvy/runtime-sbom-sha256": hashlib.sha256(inventory).hexdigest(),
        "42.ogilvy/source-sha": "b" * 40,
        "42.ogilvy/execution-approval-sha256": "d" * 64,
        "42.ogilvy/origin-registry-sha256": profile.origin_registry_sha256,
        "42.ogilvy/resource-manifest-sha256": profile.resource_manifest_sha256,
    }
    annotations["42.ogilvy/deployment-manifest-sha256"] = cli.canonical_digest(
        cli._deployment_manifest(
            annotations=annotations,
            task=cli._task_authority({"template": task}, execution=True),
            invocation_arguments=arguments,
            profile=profile,
        )
    )
    payload = {
        "execution": {
            "name": f"{profile.job_resource}/executions/exe-1",
            "job": profile.job_resource,
            "annotations": annotations,
            "template": deepcopy(task),
        },
        "job": {
            "name": profile.job_resource,
            "template": {"annotations": annotations, "template": deepcopy(task)},
        },
    }
    return cli, payload, arguments, distributions


def test_runtime_identity_binds_the_short_execution_job_id(tmp_path: Path, monkeypatch) -> None:
    cli, payload, arguments, distributions = _runtime_authority(tmp_path, monkeypatch)
    payload["execution"]["job"] = "intelligence-42-brain-staging"
    identity = cli._verify_runtime_identity(
        payload=payload,
        invocation_arguments=arguments,
        distributions=distributions,
    )
    assert identity is not None
    for wrong in ("intelligence-42-brain-staging-other", "trends-engine-oi-brain-staging", ""):
        payload["execution"]["job"] = wrong
        with pytest.raises(cli.RuntimeIdentityRefusal, match="parent job"):
            cli._verify_runtime_identity(
                payload=payload,
                invocation_arguments=arguments,
                distributions=distributions,
            )


def test_fake_control_plane_reproduces_the_exact_execution_and_job_authority(
    tmp_path: Path, monkeypatch
) -> None:
    cli, payload, arguments, distributions = _runtime_authority(tmp_path, monkeypatch)
    identity = cli._verify_runtime_identity(
        payload=payload,
        invocation_arguments=arguments,
        distributions=distributions,
    )
    assert identity.source_sha == "b" * 40
    assert (
        identity.dependency_lock_sha256
        == payload["execution"]["annotations"]["42.ogilvy/dependency-lock-sha256"]
    )


@pytest.mark.parametrize(
    ("name", "mutate"),
    [
        ("missing_execution", lambda p: p.pop("execution")),
        ("foreign_parent", lambda p: p["execution"].update(job="projects/p/locations/r/jobs/x")),
        (
            "mutable_image",
            lambda p: p["execution"]["template"]["containers"][0].update(
                image="us-central1-docker.pkg.dev/p/r/i:latest"
            ),
        ),
        (
            "contract_drift",
            lambda p: p["execution"]["annotations"].update({"42.ogilvy/contract-sha256": "f" * 64}),
        ),
        (
            "malformed_source",
            lambda p: p["execution"]["annotations"].update({"42.ogilvy/source-sha": "short"}),
        ),
        (
            "manifest_drift",
            lambda p: p["execution"]["annotations"].update(
                {"42.ogilvy/deployment-manifest-sha256": "f" * 64}
            ),
        ),
        (
            "service_identity",
            lambda p: p["execution"]["template"].update(serviceAccount="other@example.com"),
        ),
        (
            "command",
            lambda p: p["execution"]["template"]["containers"][0].update(command=["bash"]),
        ),
        (
            "arguments",
            lambda p: p["execution"]["template"]["containers"][0].update(args=["wrong.py"]),
        ),
        ("retries", lambda p: p["execution"]["template"].update(maxRetries=1)),
        (
            "writable_mount",
            lambda p: p["execution"]["template"]["containers"][0].update(
                volumeMounts=[{"name": "code", "mountPath": "/app"}]
            ),
        ),
        (
            "secret",
            lambda p: p["execution"]["template"]["containers"][0]["env"].append(
                {"name": "SECRET", "valueSource": {"secretKeyRef": {"secret": "x"}}}
            ),
        ),
        (
            "job_drift",
            lambda p: p["job"]["template"]["template"].update(maxRetries=1),
        ),
    ],
)
def test_fake_control_plane_mutations_refuse_before_data_client(
    tmp_path: Path, monkeypatch, name, mutate
) -> None:
    cli, payload, arguments, distributions = _runtime_authority(tmp_path, monkeypatch)
    mutate(payload)
    with pytest.raises(cli.RuntimeIdentityRefusal):
        cli._verify_runtime_identity(
            payload=payload,
            invocation_arguments=arguments,
            distributions=distributions,
        )


def test_image_carries_the_files_the_durable_migration_reads_at_runtime() -> None:
    docker = (ROOT / "Dockerfile.staging").read_text(encoding="utf-8")
    ignore = (ROOT / ".dockerignore").read_text(encoding="utf-8").splitlines()
    assert "COPY cloudbuild.staging.yaml ./" in docker
    assert "COPY requirements.lock ./" in docker
    assert "COPY pyproject.toml README.md LICENSE ./" in docker
    assert "COPY docs/contracts/open_intelligence_v2.md ./docs/contracts/" in docker
    assert "docs" not in ignore
    assert "docs/*" in ignore
    assert "!docs/contracts" in ignore


def test_staging_image_default_refuses_unreviewed_workload_execution() -> None:
    docker = (ROOT / "Dockerfile.staging").read_text(encoding="utf-8")
    assert 'ENTRYPOINT ["python"]' in docker
    assert "An explicit reviewed staging command is required" in docker
    assert "run_rss_now.py" not in docker


def test_staging_cloud_build_has_only_test_and_local_build_steps() -> None:
    value = yaml.safe_load((ROOT / "cloudbuild.staging.yaml").read_text(encoding="utf-8"))
    assert set(value) == {"steps", "options", "timeout"}
    assert [step["id"] for step in value["steps"]] == [
        "unit-tests",
        "build-staging-image",
    ]
    assert value["steps"][1]["args"][-1] == "."
    assert value["steps"][0]["args"] == [
        "build",
        "--file",
        "Dockerfile.tests",
        "--tag",
        "42-engine-tests:${BUILD_ID}",
        ".",
    ]
    assert value["steps"][0]["name"] == (f"gcr.io/cloud-builders/docker@{DOCKER_BUILDER_DIGEST}")
    assert value["steps"][1]["name"] == (f"gcr.io/cloud-builders/docker@{DOCKER_BUILDER_DIGEST}")
    assert "images" not in value


@pytest.mark.parametrize(
    "reference",
    [
        "gcr.io/cloud-builders/docker",
        "gcr.io/cloud-builders/docker@sha256:" + "0" * 64,
    ],
)
def test_staging_cloud_build_rejects_unpinned_or_wrong_builder(reference) -> None:
    value = yaml.safe_load((ROOT / "cloudbuild.staging.yaml").read_text(encoding="utf-8"))
    for index in (0, 1):
        value["steps"][index]["name"] = reference
        with pytest.raises(AssertionError):
            assert value["steps"][index]["name"] == (
                f"gcr.io/cloud-builders/docker@{DOCKER_BUILDER_DIGEST}"
            )


def test_runtime_identity_binds_the_durable_job_environment(tmp_path: Path, monkeypatch) -> None:
    # The durable deploy path gives every job BIGQUERY_DATASET, GCP_PROJECT and TRENDS_ENV, and
    # the approval contract binds that set. The Brain verifier must bind the same set: on
    # 3 September 2026 it demanded two variables against a job carrying three and refused
    # its own deployment with identity_refused.
    from scripts.staging import deploy_open_intelligence_job as deployer
    from src.analysis.open_intelligence import execution_approval

    assert deployer.BRAIN_ENVIRONMENT == execution_approval._DEFAULT_ENVIRONMENT
    cli, payload, arguments, distributions = _runtime_authority(tmp_path, monkeypatch)
    live = [
        {"name": "BIGQUERY_DATASET", "value": "trends_v2_staging"},
        {"name": "GCP_PROJECT", "value": "ogilvy-trends-v2"},
        {"name": "TRENDS_ENV", "value": "staging"},
    ]
    tasks = (payload["execution"]["template"], payload["job"]["template"]["template"])
    for task in tasks:
        task["containers"][0]["env"] = [dict(item) for item in live]
    identity = cli._verify_runtime_identity(
        payload=payload, invocation_arguments=arguments, distributions=distributions
    )
    assert identity is not None
    for task in tasks:
        task["containers"][0]["env"] = [dict(item) for item in live[:1] + live[2:]]
    with pytest.raises(cli.RuntimeIdentityRefusal, match="runtime configuration"):
        cli._verify_runtime_identity(
            payload=payload, invocation_arguments=arguments, distributions=distributions
        )


def test_runtime_identity_manifest_carries_the_operation_the_deployer_binds(
    tmp_path: Path, monkeypatch
) -> None:
    # The durable deployer's manifest names its operation; the Brain rebuilt the manifest
    # without it, so its digest never matched the job annotation and every staged Brain
    # execution on 3 September 2026 refused "control-plane deployment manifest differs".

    from scripts.staging import deploy_open_intelligence_job as deployer
    from src.analysis.open_intelligence import execution_generations, execution_origins
    from src.analysis.open_intelligence.brain_contract import canonical_digest

    cli, payload, arguments, _distributions = _runtime_authority(tmp_path, monkeypatch)
    execution = payload["execution"]
    task = cli._task_authority(execution, execution=True)
    manifest = cli._deployment_manifest(
        annotations=execution["annotations"],
        task=task,
        invocation_arguments=arguments,
        profile=cli._brain_profile(),
    )
    assert manifest["operation"] == "brain_read"
    annotations = execution["annotations"]
    # The deployer's v2 route renders the same job from the active generation's fresh
    # Brain origin, handed over exactly as the loader freezes it.
    generation = execution_generations.active_generation()
    row = next(
        origin
        for origin in generation.registry.values()
        if origin.manifest_version == deployer.MANIFEST_V2
        and "brain_read" in origin.operation_bindings
    )
    origin = execution_origins.select_origin(
        manifest_version=row.manifest_version,
        contract_sha256=row.contract_sha256,
        mode="new_approval",
        registry=generation.registry,
    )
    desired = deployer.desired_operation_job(
        "brain_read",
        task["image"],
        annotations["42.ogilvy/source-sha"],
        annotations["42.ogilvy/dependency-lock-sha256"],
        annotations["42.ogilvy/runtime-sbom-sha256"],
        arguments=(cli._BRAIN_SCRIPT, *arguments),
        environment=deployer.BRAIN_ENVIRONMENT,
        secrets=(),
        execution_approval_sha256=annotations["42.ogilvy/execution-approval-sha256"],
        origin=origin,
        generation=generation,
    )
    assert desired.manifest_version == deployer.MANIFEST_V2
    assert canonical_digest(manifest) == canonical_digest(
        deployer.brain_deployment_manifest(desired)
    )
    assert manifest["operation"] == desired.operation
    assert dict(desired.annotations) == {
        name: value
        for name, value in annotations.items()
        if name != "42.ogilvy/deployment-manifest-sha256"
    } | {"42.ogilvy/deployment-manifest-sha256": canonical_digest(manifest)}
