-- Daily cross-trend executive summary.
--
-- Single row per (trend_date) carrying the second-pass Gemini summary
-- that reads across all 24 per-topic briefs and produces one cohesive
-- "Today in SSA" narrative for the top of the email digest. This is
-- the strategic AI layer above the per-topic briefs: stakeholders who
-- skim the email see the through-line in one paragraph before deciding
-- whether to scroll into the cards.
--
-- Persisted (not just in-memory) so the dashboard can render a
-- timeline of daily summaries and the operator can audit which days
-- produced strong narratives versus thin ones.
CREATE TABLE IF NOT EXISTS `{project}.{dataset}.daily_summary` (
  summary_id STRING NOT NULL,
  trend_date DATE NOT NULL,
  summary_text STRING,
  through_line STRING,
  call_to_action STRING,
  markets ARRAY<STRING>,
  brief_count INT64,
  key_topics ARRAY<STRING>,
  rising_topics ARRAY<STRING>,
  gemini_model STRING,
  prompt_tokens INT64,
  completion_tokens INT64,
  -- Seed score topline (add_seed_recommend_column.py): optional follow-vs-seed
  -- recommendation naming the topic best positioned to drive Nanobanana/Lyria.
  seed_recommend STRING,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY trend_date
OPTIONS (
  description = 'Cross-trend daily executive summary generated by a second Gemini pass over the per-topic briefs.'
);
