CREATE TABLE IF NOT EXISTS `{project}.{dataset}.source_performance_daily_v2` (
  client_scope_id STRING NOT NULL OPTIONS(description = 'Resolved client scope.'),
  market_scope ARRAY<STRING> OPTIONS(description = 'Markets resolved for the run.'),
  brand_config_id STRING NOT NULL OPTIONS(description = 'Resolved brand configuration.'),
  audience_lens_ids ARRAY<STRING> OPTIONS(description = 'Resolved audience lenses, possibly empty.'),
  theme_id STRING NOT NULL OPTIONS(description = 'Resolved theme.'),
  run_id STRING NOT NULL OPTIONS(description = 'Performance snapshot run.'),
  contract_version STRING NOT NULL OPTIONS(description = 'Contract used by the writer.'),
  source_performance_id STRING NOT NULL OPTIONS(description = 'Deterministic row identifier.'),
  metric_date DATE NOT NULL OPTIONS(description = 'Daily metric date.'),
  vendor STRING NOT NULL OPTIONS(description = 'Vendor identifier.'),
  http_method STRING NOT NULL OPTIONS(description = 'Upper case HTTP method.'),
  route_path STRING NOT NULL OPTIONS(description = 'Canonical route path beginning with slash.'),
  endpoint_id STRING NOT NULL OPTIONS(description = 'Digest derived from http_method plus route_path.'),
  route_role STRING NOT NULL OPTIONS(description = 'Evidence, utility_balance, utility_catalog, identity_discovery, identity_hygiene, or inventory.'),
  source_family STRING NOT NULL OPTIONS(description = 'Normalized independent source family.'),
  market STRING OPTIONS(description = 'Lower case market when metrics are market specific.'),
  status STRING NOT NULL OPTIONS(description = 'Active, pilot, available_unwired, blocked, permanently_rejected, or inventory_only.'),
  calls INT64 OPTIONS(description = 'Allowed only for active or pilot.'),
  credits NUMERIC OPTIONS(description = 'Allowed only for active or pilot.'),
  `rows` INT64 OPTIONS(description = 'Distinct items the route returned; present for active and permanently_rejected inventory routes. For identity roles, normalized result count after deterministic normalization and deduplication.'),
  integrity FLOAT64 OPTIONS(description = 'Bounded 0 to 1. Allowed only for active or pilot.'),
  geo_precision FLOAT64 OPTIONS(description = 'Bounded 0 to 1. Allowed only for active or pilot.'),
  unique_lift FLOAT64 OPTIONS(description = 'Marginal downstream row count, candidate terms plus evidence rows only this route produced; present for active and permanently_rejected inventory routes.'),
  last_success_at TIMESTAMP OPTIONS(description = 'Allowed only for active or pilot.'),
  downstream_consumers ARRAY<STRING> OPTIONS(description = 'Allowed only for active or pilot.'),
  official_capability STRING NOT NULL OPTIONS(description = 'Sanitized official capability statement.'),
  official_parameters ARRAY<STRING> OPTIONS(description = 'Sanitized official parameters.'),
  official_price_components ARRAY<STRUCT<
    meter STRING NOT NULL,
    billing_basis STRING NOT NULL,
    currency STRING NOT NULL,
    unit STRING NOT NULL,
    quantity NUMERIC NOT NULL,
    source_url STRING NOT NULL,
    checked_at TIMESTAMP NOT NULL,
    amount NUMERIC,
    minimum_amount NUMERIC,
    maximum_amount NUMERIC,
    tier_condition STRING
  >> OPTIONS(description = 'Exact price components. Required for available_unwired; nested modes are listed below.'),
  blocking_reason STRING OPTIONS(description = 'Required only for blocked.'),
  kill_test_result STRING OPTIONS(description = 'Required for permanently_rejected: the kill test reason, equal to blocking_reason.'),
  review_date DATE OPTIONS(description = 'Null. Reserved for a reviewed rejection, which no writer produces.'),
  last_checked_at TIMESTAMP NOT NULL OPTIONS(description = 'Catalog or live drift check time.'),
  balance NUMERIC OPTIONS(description = 'Free balance observation on the canonical balance route only.'),
  observed_at TIMESTAMP OPTIONS(description = 'Balance observation time on the canonical balance route.'),
  balance_read_status STRING OPTIONS(description = 'Ok or unknown on the canonical balance route.'),
  recent_deductions NUMERIC OPTIONS(description = 'Measured deductions bridging the prior and current successful balance observations.'),
  deductions_interval STRUCT<
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL
  > OPTIONS(description = 'Exact measurement interval with nested modes below.'),
  funding_math_status STRING OPTIONS(description = 'Complete or unknown on the balance route.'),
  funded_increase_amount NUMERIC OPTIONS(description = 'Derived top up amount when funding math is complete.'),
  funded_increase_observed BOOL OPTIONS(description = 'Fail closed funding gate. False on unknown, null on nonbalance routes.'),
  selected_top_up_credits NUMERIC OPTIONS(description = 'Commercially selected top up amount, not proof of payment or funding.'),
  baseline_credits_per_day NUMERIC OPTIONS(description = 'Measured completed day baseline.'),
  baseline_window STRUCT<
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    completed_days INT64 NOT NULL
  > OPTIONS(description = 'Measured baseline window with nested modes below.'),
  runway_days NUMERIC OPTIONS(description = 'Measured runway.'),
  monthly_optional_credit_cap NUMERIC OPTIONS(description = 'Required balance route control, fixed at 25,000 until a new approval.'),
  monthly_optional_credits_used NUMERIC OPTIONS(description = 'Measured optional lane credits in the current calendar month.'),
  optional_calls_enabled BOOL OPTIONS(description = 'Required on the balance route, null on other routes.'),
  platform STRING OPTIONS(description = 'Canonical vendor platform for inventory rows.'),
  resource STRING OPTIONS(description = 'Canonical vendor resource for inventory rows.'),
  catalog_digest STRING OPTIONS(description = 'Approved catalog snapshot digest for inventory rows.'),
  official_credits NUMERIC OPTIONS(description = 'Vendor documented credit quantity for the inventory route.'),
  official_credits_label STRING OPTIONS(description = 'Vendor documented credit label for the inventory route.'),
  official_archetype STRING OPTIONS(description = 'Vendor documented route archetype.'),
  catalog_paginated BOOL OPTIONS(description = 'Vendor catalog pagination flag.'),
  catalog_metered BOOL OPTIONS(description = 'Vendor catalog metering flag.'),
  cache_ttl_seconds INT64 OPTIONS(description = 'Vendor catalog cache lifetime in seconds.'),
  delivery STRING OPTIONS(description = 'Vendor documented delivery mode.'),
  docs_url STRING OPTIONS(description = 'Sanitized official documentation URL.'),
  vendor_family STRING OPTIONS(description = 'Canonical supplier family.'),
  channel_family STRING OPTIONS(description = 'Canonical channel family. Equals source_family compatibility alias.'),
  funded_lane STRING OPTIONS(description = 'Funded execution lane when a route is piloted under a bounded stage.')
)
PARTITION BY metric_date
CLUSTER BY vendor, status, source_family, market
OPTIONS (
  description = 'One daily row per vendor route and observed market. Catalog only routes use null market. Natural key: source_performance_id.'
);
